//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConorFoxWebsite.WebServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/ConorFoxProject")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentForenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Course {
            get {
                return this.CourseField;
            }
            set {
                if ((this.CourseField.Equals(value) != true)) {
                    this.CourseField = value;
                    this.RaisePropertyChanged("Course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((this.CreatorField.Equals(value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastActivity {
            get {
                return this.LastActivityField;
            }
            set {
                if ((this.LastActivityField.Equals(value) != true)) {
                    this.LastActivityField = value;
                    this.RaisePropertyChanged("LastActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentEmail {
            get {
                return this.StudentEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentEmailField, value) != true)) {
                    this.StudentEmailField = value;
                    this.RaisePropertyChanged("StudentEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentForename {
            get {
                return this.StudentForenameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentForenameField, value) != true)) {
                    this.StudentForenameField = value;
                    this.RaisePropertyChanged("StudentForename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentSurname {
            get {
                return this.StudentSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentSurnameField, value) != true)) {
                    this.StudentSurnameField = value;
                    this.RaisePropertyChanged("StudentSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentTitle {
            get {
                return this.StudentTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentTitleField, value) != true)) {
                    this.StudentTitleField = value;
                    this.RaisePropertyChanged("StudentTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staff", Namespace="http://schemas.datacontract.org/2004/07/ConorFoxProject")]
    [System.SerializableAttribute()]
    public partial class Staff : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffForenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StaffIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Course {
            get {
                return this.CourseField;
            }
            set {
                if ((this.CourseField.Equals(value) != true)) {
                    this.CourseField = value;
                    this.RaisePropertyChanged("Course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((this.CreatorField.Equals(value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastActivity {
            get {
                return this.LastActivityField;
            }
            set {
                if ((this.LastActivityField.Equals(value) != true)) {
                    this.LastActivityField = value;
                    this.RaisePropertyChanged("LastActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffEmail {
            get {
                return this.StaffEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffEmailField, value) != true)) {
                    this.StaffEmailField = value;
                    this.RaisePropertyChanged("StaffEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffForename {
            get {
                return this.StaffForenameField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffForenameField, value) != true)) {
                    this.StaffForenameField = value;
                    this.RaisePropertyChanged("StaffForename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StaffId {
            get {
                return this.StaffIdField;
            }
            set {
                if ((this.StaffIdField.Equals(value) != true)) {
                    this.StaffIdField = value;
                    this.RaisePropertyChanged("StaffId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffSurname {
            get {
                return this.StaffSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffSurnameField, value) != true)) {
                    this.StaffSurnameField = value;
                    this.RaisePropertyChanged("StaffSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffTitle {
            get {
                return this.StaffTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffTitleField, value) != true)) {
                    this.StaffTitleField = value;
                    this.RaisePropertyChanged("StaffTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/ConorFoxProject")]
    [System.SerializableAttribute()]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalNotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastDateEditedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LastUserEditedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModuleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RepeatsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalNotes {
            get {
                return this.AdditionalNotesField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalNotesField, value) != true)) {
                    this.AdditionalNotesField = value;
                    this.RaisePropertyChanged("AdditionalNotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Course {
            get {
                return this.CourseField;
            }
            set {
                if ((this.CourseField.Equals(value) != true)) {
                    this.CourseField = value;
                    this.RaisePropertyChanged("Course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventDescription {
            get {
                return this.EventDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.EventDescriptionField, value) != true)) {
                    this.EventDescriptionField = value;
                    this.RaisePropertyChanged("EventDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventTitle {
            get {
                return this.EventTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.EventTitleField, value) != true)) {
                    this.EventTitleField = value;
                    this.RaisePropertyChanged("EventTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventType {
            get {
                return this.EventTypeField;
            }
            set {
                if ((this.EventTypeField.Equals(value) != true)) {
                    this.EventTypeField = value;
                    this.RaisePropertyChanged("EventType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastDateEdited {
            get {
                return this.LastDateEditedField;
            }
            set {
                if ((this.LastDateEditedField.Equals(value) != true)) {
                    this.LastDateEditedField = value;
                    this.RaisePropertyChanged("LastDateEdited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LastUserEdited {
            get {
                return this.LastUserEditedField;
            }
            set {
                if ((this.LastUserEditedField.Equals(value) != true)) {
                    this.LastUserEditedField = value;
                    this.RaisePropertyChanged("LastUserEdited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Module {
            get {
                return this.ModuleField;
            }
            set {
                if ((this.ModuleField.Equals(value) != true)) {
                    this.ModuleField = value;
                    this.RaisePropertyChanged("Module");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Repeats {
            get {
                return this.RepeatsField;
            }
            set {
                if ((this.RepeatsField.Equals(value) != true)) {
                    this.RepeatsField = value;
                    this.RaisePropertyChanged("Repeats");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Room {
            get {
                return this.RoomField;
            }
            set {
                if ((this.RoomField.Equals(value) != true)) {
                    this.RoomField = value;
                    this.RaisePropertyChanged("Room");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentInvite", Namespace="http://schemas.datacontract.org/2004/07/ConorFoxProject")]
    [System.SerializableAttribute()]
    public partial class StudentInvite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AttendingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentInviteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Attending {
            get {
                return this.AttendingField;
            }
            set {
                if ((this.AttendingField.Equals(value) != true)) {
                    this.AttendingField = value;
                    this.RaisePropertyChanged("Attending");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentInviteId {
            get {
                return this.StudentInviteIdField;
            }
            set {
                if ((this.StudentInviteIdField.Equals(value) != true)) {
                    this.StudentInviteIdField = value;
                    this.RaisePropertyChanged("StudentInviteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StaffInvite", Namespace="http://schemas.datacontract.org/2004/07/ConorFoxProject")]
    [System.SerializableAttribute()]
    public partial class StaffInvite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AttendingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EventIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StaffIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StaffInviteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Attending {
            get {
                return this.AttendingField;
            }
            set {
                if ((this.AttendingField.Equals(value) != true)) {
                    this.AttendingField = value;
                    this.RaisePropertyChanged("Attending");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StaffId {
            get {
                return this.StaffIdField;
            }
            set {
                if ((this.StaffIdField.Equals(value) != true)) {
                    this.StaffIdField = value;
                    this.RaisePropertyChanged("StaffId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StaffInviteId {
            get {
                return this.StaffInviteIdField;
            }
            set {
                if ((this.StaffInviteIdField.Equals(value) != true)) {
                    this.StaffInviteIdField = value;
                    this.RaisePropertyChanged("StaffInviteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceReference.IWebsiteService")]
    public interface IWebsiteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/StudentLogin", ReplyAction="http://tempuri.org/IWebsiteService/StudentLoginResponse")]
        ConorFoxWebsite.WebServiceReference.Student StudentLogin(string studentEmail, string studentPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/StudentLogin", ReplyAction="http://tempuri.org/IWebsiteService/StudentLoginResponse")]
        System.Threading.Tasks.Task<ConorFoxWebsite.WebServiceReference.Student> StudentLoginAsync(string studentEmail, string studentPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/StaffLogin", ReplyAction="http://tempuri.org/IWebsiteService/StaffLoginResponse")]
        ConorFoxWebsite.WebServiceReference.Staff StaffLogin(string staffEmail, string staffPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/StaffLogin", ReplyAction="http://tempuri.org/IWebsiteService/StaffLoginResponse")]
        System.Threading.Tasks.Task<ConorFoxWebsite.WebServiceReference.Staff> StaffLoginAsync(string staffEmail, string staffPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/EventSummary", ReplyAction="http://tempuri.org/IWebsiteService/EventSummaryResponse")]
        ConorFoxWebsite.WebServiceReference.Event EventSummary(int userId, int userType, int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/EventSummary", ReplyAction="http://tempuri.org/IWebsiteService/EventSummaryResponse")]
        System.Threading.Tasks.Task<ConorFoxWebsite.WebServiceReference.Event> EventSummaryAsync(int userId, int userType, int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/ReturnEventDetail", ReplyAction="http://tempuri.org/IWebsiteService/ReturnEventDetailResponse")]
        ConorFoxWebsite.WebServiceReference.Event ReturnEventDetail(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/ReturnEventDetail", ReplyAction="http://tempuri.org/IWebsiteService/ReturnEventDetailResponse")]
        System.Threading.Tasks.Task<ConorFoxWebsite.WebServiceReference.Event> ReturnEventDetailAsync(int eventId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/StudentsEvents", ReplyAction="http://tempuri.org/IWebsiteService/StudentsEventsResponse")]
        ConorFoxWebsite.WebServiceReference.Event[] StudentsEvents(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/StudentsEvents", ReplyAction="http://tempuri.org/IWebsiteService/StudentsEventsResponse")]
        System.Threading.Tasks.Task<ConorFoxWebsite.WebServiceReference.Event[]> StudentsEventsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/StaffEvents", ReplyAction="http://tempuri.org/IWebsiteService/StaffEventsResponse")]
        ConorFoxWebsite.WebServiceReference.Event[] StaffEvents(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/StaffEvents", ReplyAction="http://tempuri.org/IWebsiteService/StaffEventsResponse")]
        System.Threading.Tasks.Task<ConorFoxWebsite.WebServiceReference.Event[]> StaffEventsAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/StudentsInvites", ReplyAction="http://tempuri.org/IWebsiteService/StudentsInvitesResponse")]
        ConorFoxWebsite.WebServiceReference.StudentInvite[] StudentsInvites(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/StudentsInvites", ReplyAction="http://tempuri.org/IWebsiteService/StudentsInvitesResponse")]
        System.Threading.Tasks.Task<ConorFoxWebsite.WebServiceReference.StudentInvite[]> StudentsInvitesAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/StaffInvites", ReplyAction="http://tempuri.org/IWebsiteService/StaffInvitesResponse")]
        ConorFoxWebsite.WebServiceReference.StaffInvite[] StaffInvites(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/StaffInvites", ReplyAction="http://tempuri.org/IWebsiteService/StaffInvitesResponse")]
        System.Threading.Tasks.Task<ConorFoxWebsite.WebServiceReference.StaffInvite[]> StaffInvitesAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/ConfirmStudentInvite", ReplyAction="http://tempuri.org/IWebsiteService/ConfirmStudentInviteResponse")]
        bool ConfirmStudentInvite(int eventId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/ConfirmStudentInvite", ReplyAction="http://tempuri.org/IWebsiteService/ConfirmStudentInviteResponse")]
        System.Threading.Tasks.Task<bool> ConfirmStudentInviteAsync(int eventId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/ConfirmStaffInvite", ReplyAction="http://tempuri.org/IWebsiteService/ConfirmStaffInviteResponse")]
        bool ConfirmStaffInvite(int eventId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebsiteService/ConfirmStaffInvite", ReplyAction="http://tempuri.org/IWebsiteService/ConfirmStaffInviteResponse")]
        System.Threading.Tasks.Task<bool> ConfirmStaffInviteAsync(int eventId, int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebsiteServiceChannel : ConorFoxWebsite.WebServiceReference.IWebsiteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebsiteServiceClient : System.ServiceModel.ClientBase<ConorFoxWebsite.WebServiceReference.IWebsiteService>, ConorFoxWebsite.WebServiceReference.IWebsiteService {
        
        public WebsiteServiceClient() {
        }
        
        public WebsiteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebsiteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebsiteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebsiteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConorFoxWebsite.WebServiceReference.Student StudentLogin(string studentEmail, string studentPassword) {
            return base.Channel.StudentLogin(studentEmail, studentPassword);
        }
        
        public System.Threading.Tasks.Task<ConorFoxWebsite.WebServiceReference.Student> StudentLoginAsync(string studentEmail, string studentPassword) {
            return base.Channel.StudentLoginAsync(studentEmail, studentPassword);
        }
        
        public ConorFoxWebsite.WebServiceReference.Staff StaffLogin(string staffEmail, string staffPassword) {
            return base.Channel.StaffLogin(staffEmail, staffPassword);
        }
        
        public System.Threading.Tasks.Task<ConorFoxWebsite.WebServiceReference.Staff> StaffLoginAsync(string staffEmail, string staffPassword) {
            return base.Channel.StaffLoginAsync(staffEmail, staffPassword);
        }
        
        public ConorFoxWebsite.WebServiceReference.Event EventSummary(int userId, int userType, int eventId) {
            return base.Channel.EventSummary(userId, userType, eventId);
        }
        
        public System.Threading.Tasks.Task<ConorFoxWebsite.WebServiceReference.Event> EventSummaryAsync(int userId, int userType, int eventId) {
            return base.Channel.EventSummaryAsync(userId, userType, eventId);
        }
        
        public ConorFoxWebsite.WebServiceReference.Event ReturnEventDetail(int eventId) {
            return base.Channel.ReturnEventDetail(eventId);
        }
        
        public System.Threading.Tasks.Task<ConorFoxWebsite.WebServiceReference.Event> ReturnEventDetailAsync(int eventId) {
            return base.Channel.ReturnEventDetailAsync(eventId);
        }
        
        public ConorFoxWebsite.WebServiceReference.Event[] StudentsEvents(int userId) {
            return base.Channel.StudentsEvents(userId);
        }
        
        public System.Threading.Tasks.Task<ConorFoxWebsite.WebServiceReference.Event[]> StudentsEventsAsync(int userId) {
            return base.Channel.StudentsEventsAsync(userId);
        }
        
        public ConorFoxWebsite.WebServiceReference.Event[] StaffEvents(int userId) {
            return base.Channel.StaffEvents(userId);
        }
        
        public System.Threading.Tasks.Task<ConorFoxWebsite.WebServiceReference.Event[]> StaffEventsAsync(int userId) {
            return base.Channel.StaffEventsAsync(userId);
        }
        
        public ConorFoxWebsite.WebServiceReference.StudentInvite[] StudentsInvites(int userId) {
            return base.Channel.StudentsInvites(userId);
        }
        
        public System.Threading.Tasks.Task<ConorFoxWebsite.WebServiceReference.StudentInvite[]> StudentsInvitesAsync(int userId) {
            return base.Channel.StudentsInvitesAsync(userId);
        }
        
        public ConorFoxWebsite.WebServiceReference.StaffInvite[] StaffInvites(int userId) {
            return base.Channel.StaffInvites(userId);
        }
        
        public System.Threading.Tasks.Task<ConorFoxWebsite.WebServiceReference.StaffInvite[]> StaffInvitesAsync(int userId) {
            return base.Channel.StaffInvitesAsync(userId);
        }
        
        public bool ConfirmStudentInvite(int eventId, int userId) {
            return base.Channel.ConfirmStudentInvite(eventId, userId);
        }
        
        public System.Threading.Tasks.Task<bool> ConfirmStudentInviteAsync(int eventId, int userId) {
            return base.Channel.ConfirmStudentInviteAsync(eventId, userId);
        }
        
        public bool ConfirmStaffInvite(int eventId, int userId) {
            return base.Channel.ConfirmStaffInvite(eventId, userId);
        }
        
        public System.Threading.Tasks.Task<bool> ConfirmStaffInviteAsync(int eventId, int userId) {
            return base.Channel.ConfirmStaffInviteAsync(eventId, userId);
        }
    }
}
